GNUmakefile: make dev uses packer for install
ethanmdavidson/packer-plugin-git pull request #121
Opened 2024-03-15 19:52 UTC by lbajolet-hashicorp

When building the development version of the plugin, we now use
`packer plugins install` for that instead of moving it to the plugins
directory manually.

This target will require Packer 1.10.2 and above to function, as prior
versions don't support instaling pre-release versions of a plugin with
that command.

2024-03-23 16:39 UTC, ethanmdavidson requested changes
The minimum packer version for development specified in the readme needs to be updated as well. See [line 61](https://github.com/ethanmdavidson/packer-plugin-git/blob/main/README.md?plain=1#L61).

2024-03-23 16:39 UTC, ethanmdavidson commented on GNUmakefile
> +dev:
```suggestion
dev: phony
```

Needs a dependency on `phony`. See lines 54-60 for details

2024-03-26 13:59 UTC, lbajolet-hashicorp commented
Hi @ethanmdavidson,

Thanks for the review, I just updated both the Makefile and the README with your requested changes, this is ready for a second round of reviews now I'd think.

2024-04-01 11:08 UTC, ethanmdavidson approved these changes

2024-04-01 11:08 UTC, merged